set(VCPKG_TARGET_ARCHITECTURE x64)
if (WIN32)
    set(VCPKG_CRT_LINKAGE static)
    set(VCPKG_LIBRARY_LINKAGE static)
else()
    set(VCPKG_CRT_LINKAGE dynamic)
    set(VCPKG_LIBRARY_LINKAGE static)
    if(PORT MATCHES "ffmpeg")
        set(VCPKG_LIBRARY_LINKAGE dynamic)
    endif()
    set(VCPKG_CMAKE_SYSTEM_NAME Linux)
endif()
